server:
  port: 18080
  tomcat:
    max-http-header-size: 65536
spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    #发件人
    username: gaoyuanming_1@163.com
    #授权码
    password: a123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logistics?serverTimezone=Asia/Shanghai
    username: root
    password: 48926246
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false